### ISSUE TITLE
Installation instructions wrong

### ISSUE THREAD

**Issue by brxxlstxrs** [eylles/pywal16#23]
How install pywal16 (not pywal?)

**Comment by eylles** [comment]
ah, yes sorry for a time i intended to request ownership of the name 'pywal' to pypi since it has been unmaintained for years and as such abstained from uploading a pywal16 package to pypi, currently i no longer see a benefit from doing that and my plan has changed to clean up the metadata on setup.py, address #17 and #22 (even if partially) then cut a release tag and upload that to pypi.

until then the currently reccomended installation is to do a manual install:

```sh
git clone https://github.com/eylles/pywal16
cd pywal
pip3 install --user .
```

however mind you that PEP668 added the marking of system python packages as externally managed, therefore you have to either create a `virtual environtment` first, pass the `--break-system-packages` flag to pip, or install `pipx` from your distro's packages and substitute `pip3` with `pipx` on the above command.

**Comment by brxxlstxrs** [comment]
mb you forgot the write create a `virtual environtment` first, **or** pass the `--break-system-packages` flag to pip?

**Comment by eylles** [comment]
well, the python team gives 2 recommendations, to create a virtual environment for all your pip managed packages or to use pipx so that every package has it's own virtual environment, the second is recommended to avoid issues with dependencies mismatching across packages tho they have been working on reducing those as much as possible.

**Comment by brxxlstxrs** [comment]
also why i need this '--user` when pipx? i know pep668 streak to install python packages via os package manager for example on arch for pywal `sudo pacman -S python-pywal`

**Comment by brxxlstxrs** [comment]
mb just `pipx install <package>`?

**Comment by eylles** [comment]
It should be

```sh
git clone https://github.com/eylles/pywal16
cd pywal16
pipx install --spec . pywal
```

But will check once i'm at home.

**Comment by brxxlstxrs** [comment]
> It should be
> 
> ```shell
> git clone https://github.com/eylles/pywal16
> cd pywal16
> pipx install --spec . pywal
> ```
> 
> But will check once i'm at home.
If it works, close

**Comment by eylles** [comment]
I have not tested tbh, i'm working on https://github.com/eylles/pywal16-libadwaita once i have documentation and the scripts to "build" themes i'm working on the next release of pywal16 which WILL be uploaded to pypi

**Comment by brxxlstxrs** [comment]
> I have not tested tbh, i'm working on https://github.com/eylles/pywal16-libadwaita once i have documentation and the scripts to "build" themes i'm working on the next release of pywal16 which WILL be uploaded to pypi

@eylles ok

**Comment by eylles** [comment]
okay proper install instructions with pipx

```sh
git clone [github.com/eylles/pywal16](https://github.com/eylles/pywal16)
cd pywal16
pipx install .
```

will update the wiki later.

**Comment by AyushmaanAggarwal** [comment]
Since pywal16 has been added to [pypi](https://pypi.org/project/pywal16/#description), updating the install instructions on this git repo would be much appreciated. It took me a while to realize that I could install it directly from pip without cloning the repo, especially since the install instructions still point to the old repo with the 'pip install pywal' command

**Comment by eylles** [comment]
ah sorry i had forgotten to update the wiki.

@AyushmaanAggarwal does this instruction set seem okay ? https://github.com/eylles/pywal16/wiki/Installation#pip-install

**Comment by AyushmaanAggarwal** [comment]
Looks great!
