### ISSUE TITLE
16 colors output only with --cols16 option

### ISSUE THREAD

**Issue by lioncahir** [eylles/pywal16#54]
By default it seems that wal only extracts 8 colors from a wallpaper, with `wal -i /path/to/image`. Only when I use `wal --cols16 -i /path/to/image`, I get nice 16 colors. Is this expected behavior? If so, can it be mentioned in the "Getting started" page? Thank you!

**Comment by eylles** [comment]
Yes it is expected behaviour, pywal16 by default is retrocompatible with the expected pywal behaviour (or at least is intended to) so to do get 16 color shades you need to use the --cols16 flag, despite having quite some releases i've just began to really edit the wiki, so i'll edit as soon as i get home.

**Comment by eylles** [comment]
forgot to mention, wiki is updated now!     
https://github.com/eylles/pywal16/wiki/Getting-Started
