### ISSUE TITLE
Directories inside templates folder

### ISSUE THREAD

**Issue by Reyshyram** [eylles/pywal16#66]
Hi,

Is it possible to create subdirectories within the `templates` folder, each containing templates that can then be exported to the `.cache/wal` folder?

I attempted to create a template within a subfolder, but it seems that Pywal skipped the entire directory.

**Comment by eylles** [comment]
sorry, forgot to answer this.

no is not possible, the way that pywal has worked since dylan added the option to have custom user templates was that every file in the program OR user `templates` directory is treated as a template but none of the directories is checked recursively for more files inside sub directories.

as for the feature i have at a couple points through the life of pywal16 thought of adding the capability to deal with sub directories but it is hard, ugly and bug prone work that isn't helped by the fact that the code in charge of exporting templates already got at least 2 bugs lurking inside of which i'm not sure how either happen, i want to take the time and dissect that code commit per commit but haven't had the chance.

**Comment by Reyshyram** [comment]
Okay, thanks for answering!

**Comment by eylles** [comment]
emphasis on such feature not being something i can take on at the time, i would have to first fix the code that exports templates before adding anything else to it.

**Comment by Reyshyram** [comment]
Thanks!
