### ISSUE TITLE
Noticed an inconsistency when using '-p NAME'

### ISSUE THREAD

**Issue by vaskark** [eylles/pywal16#71]
I made some adjustments to my colors.json template, changing:

```
"cursor": "{cursor}"
to 
"cursor": "{color6}"
```

Now, when I save the theme with '-p NAME' my change is not being recognized in the newly saved file. When I looked in the `~/.cache/wal` directory I noticed my change was correct in the colors.json file (as expected), but the generated file in the schemes directory was not. And I'm assuming this file (and not colors.json) is what's getting saved/copied with the '-p' option.

Any advice would be appreciated.
Thanks.

Ubuntu 24.04
Pywal16 3.6.1 (latest git)

**Comment by eylles** [comment]
sorry it took me so long to get to this, if ya read the output of wal -h it says:
```
-p "theme_name"       permanently save theme to $XDG_CONFIG_HOME/wal/colorschemes with the specified name
```

so i'll test with my current wallpaper:
![__deutschland_drawn_by_eva_hq8nn1ef__1d76004e7853b8a82cedf3e8def525fa](https://github.com/user-attachments/assets/2bd58317-1fd0-44b6-8e11-96f518ca4517)


the output:
![image](https://github.com/user-attachments/assets/eed7cb76-8305-48fe-a231-03ed456cfde1)

okay i have already used the image, backend and lighten option for cols16, pywal found a cached colorscheme for those settings and image in `~/.cache/wal/schemes/`, but the theme `test_theme` should have been saved to `$XDG_CONFIG_HOME/wal/colorschemes`
![image](https://github.com/user-attachments/assets/e39673e6-f22d-4fa0-897f-793a16fcf6e3)

yep, it is there!
![image](https://github.com/user-attachments/assets/542682eb-a07a-4ac4-a938-c339b3a66e2e)


i should really provide a manpage for pywal so that users can do `man pywal`, will try to provide one for the next release.

any other question?

**Comment by vaskark** [comment]
None. Thank you.
