### ISSUE TITLE
still compatible with mac?

### ISSUE THREAD

**Issue by vang0130** [eylles/pywal16#87]
I just downloaded and tried to run, and I get an error: "unable to open database "/Users/.../Library/Application Support/Dock/desktoppicture.db": unable to open database file".

Does anyone know how to fix this? I am running an M3 macbook with Sonoma 14.4.

**Comment by eylles** [comment]
that is exactly what #86 is for, or at least what it is supposed to be for since i got no way to know if it actually works other than taking the word of whoever takes the time to test if it works.

if you can doing a git [install](https://github.com/eylles/pywal16/wiki/Installation) of the [macos-sonoma](https://github.com/eylles/pywal16/tree/macos-sonoma) branch and reporting back if it does actually set the wallpaper would greatly help.

**Comment by vang0130** [comment]
It does work, this is awesome! I've been trying different versions of something like this for days on and off. Please lmk if you'd like me to do any more testing, I'd be happy to help.

**Comment by eylles** [comment]
thanks, just knowing that it works is enough for the current release cycle, which speaking of should be 2 more pull requests away from the next version unless something new comes up.
